name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint || (npm run lint:fix && npm run lint)
      

      - name: Run tests with coverage
        run: npm run prebuild && npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optional for public repos
          directory: ./coverage/
          fail_ci_if_error: true

      - name: Build the application
        run: npm run build

      # - name: Build the application
      #   run: npm run build